import type { Config } from 'tailwindcss'
import { tokens } from './tokens';

const config: Config = {
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                background: tokens.colors.bg.background,
                black: tokens.colors.bg.black,
                'black-transparent': tokens.colors.bg.blackTransparent,
                white: tokens.colors.bg.white,
                transparent: tokens.colors.bg.transparent,
                card: tokens.colors.bg.card,
                slate: {
                    2: tokens.colors.bg.slate[2],
                    4: tokens.colors.bg.slate[4],
                    5: tokens.colors.bg.slate[5],
                    6: tokens.colors.bg.slate[6],
                    10: tokens.colors.text.slate[10],
                    11: tokens.colors.text.slate[11],
                    12: tokens.colors.text.slate[12],
                },
                green: {
                    3: tokens.colors.bg.states.success,
                    10: tokens.colors.bg.states.success,
                    11: tokens.colors.text.states.success,
                    500: tokens.colors.bg.states.success,
                },
                red: {
                    3: tokens.colors.bg.states.error,
                    10: tokens.colors.bg.states.error,
                    11: tokens.colors.text.states.error,
                },
                yellow: {
                    3: tokens.colors.bg.states.warning,
                    10: tokens.colors.bg.states.warning,
                    11: tokens.colors.text.states.warning,
                },
                blue: {
                    3: tokens.colors.bg.states.info,
                    11: tokens.colors.text.states.info,
                },
                violet: {
                    3: tokens.colors.bg.states.violet,
                    11: tokens.colors.text.states.violet,
                },
                gray: {
                    9: tokens.colors.text.muted,
                    10: tokens.colors.text.secondary,
                    a3: tokens.colors.border.grayA3,
                },
            },
            fontFamily: {
                sans: tokens.typography.fontFamily.sans,
                display: tokens.typography.fontFamily.display,
                domaine: tokens.typography.fontFamily.display,
                mono: tokens.typography.fontFamily.mono,
            },
            fontSize: {
                xs: tokens.typography.fontSize.caption,
                sm: tokens.typography.fontSize.small,
                base: tokens.typography.fontSize.body,
                xl: tokens.typography.fontSize.xl,
                '1.5rem': tokens.typography.fontSize.h3,
                '3rem': tokens.typography.fontSize.h2,
                '3.5rem': tokens.typography.fontSize.h1,
                '4rem': tokens.typography.fontSize.display,
                '4.8rem': tokens.typography.fontSize.displayLarge,
                '6rem': tokens.typography.fontSize.hero,
            },
            fontWeight: {
                light: tokens.typography.fontWeight.light,
                normal: tokens.typography.fontWeight.regular,
                medium: tokens.typography.fontWeight.medium,
                semibold: tokens.typography.fontWeight.semibold,
            },
            letterSpacing: {
                tighter: tokens.typography.letterSpacing.tighter,
                tight: tokens.typography.letterSpacing.tight,
                snug: tokens.typography.letterSpacing.snug,
                wide: tokens.typography.letterSpacing.wide,
            },
            lineHeight: {
                none: tokens.typography.lineHeight.none,
                tight: tokens.typography.lineHeight.tight,
                snug: tokens.typography.lineHeight.snug,
                normal: tokens.typography.lineHeight.normal,
                relaxed: tokens.typography.lineHeight.relaxed,
                loose: tokens.typography.lineHeight.loose,
            },
            spacing: {
                0.5: tokens.spacing.gap.tight,
                1: tokens.spacing.gap.base,
                1.5: '0.375rem',
                2: tokens.spacing.gap.tight,
                2.5: '0.625rem',
                3: '0.75rem',
                4: tokens.spacing.gap.base,
                5: tokens.spacing.gap.medium,
                6: tokens.spacing.padding.containerX,
                8: '2rem',
                10: '2.5rem',
                12: tokens.spacing.gap.large,
                16: tokens.spacing.gap.xl,
                20: tokens.spacing.gap.xxl,
                24: tokens.spacing.padding.sectionYLarge,
                36: '9rem',
            },
            maxWidth: {
                '3xl': tokens.grid.maxWidth['3xl'],
                '5xl': tokens.grid.maxWidth['5xl'],
                '7xl': tokens.grid.maxWidth['7xl'],
                lg: '32rem',
                md: '28rem',
            },
            borderRadius: {
                none: '0',
                sm: tokens.radius.sm,
                md: tokens.radius.md,
                lg: tokens.radius.lg,
                xl: tokens.radius.xl,
                '2xl': tokens.radius['2xl'],
                '3xl': tokens.radius['3xl'],
                full: tokens.radius.full,
            },
            boxShadow: {
                sm: tokens.shadow.sm,
                button: tokens.shadow.insetLine,
                card: tokens.shadow.cardElevation,
            },
            transitionDuration: {
                150: tokens.animation.duration.fast,
                200: tokens.animation.duration.base,
                300: tokens.animation.duration.medium,
                500: tokens.animation.duration.slow,
            },
            transitionTimingFunction: {
                DEFAULT: tokens.animation.easing.base,
                in: tokens.animation.easing.in,
                out: tokens.animation.easing.out,
                linear: tokens.animation.easing.linear,
                spring: tokens.animation.easing.spring,
            },
            backgroundImage: {
                'glow-line': tokens.colors.gradients.glowLine,
                'glow-conic': tokens.colors.gradients.glowConic,
                'glow-radial': tokens.colors.gradients.glowRadial,
                'button-bg': tokens.colors.gradients.buttonBgMap,
                'card-hover': tokens.colors.gradients.cardHoverGlow,
            },
        },
    },
    plugins: [],
}
export default config;
